# Generated by Django 3.0.4 on 2020-03-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date_pub',
        ),
    ]
